name: Deploy to Server

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server and pull changes
      uses: appleboy/ssh-action@master
      with:
        host: 162.43.49.87
        username: root
        password: stock-news$$2727
        port: 22
        script: |
          cd /var/www/server/cms-backend/
          git pull origin master